version: '3.3'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      - SA_PASSWORD=123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_volume:/var/opt/mssql
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:80"
    depends_on:
      - db
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
    - "5001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:        
      - '.:/app'
      - '/app/node_modules'
    