version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      HOST: "localhost"
      POSTGRES_USER: "UserPawel"
      POSTGRES_PASSWORD: "PasswordPawel"
      POSTGRES_DB: "postgresdb"
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - global
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - global
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
    - "5001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:        
      - '.:/app'
      - '/app/node_modules'
    networks:
      - global
volumes:
  db:
    driver: local

networks:
  global:
    